# Generated by Django 3.2.9 on 2021-11-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.CharField(default='img/events/default_event.jpg', max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('date', models.CharField(default='11/10/2021', max_length=30)),
                ('time', models.CharField(default='11:00 AM', max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.CharField(max_length=30)),
                ('attendees', models.IntegerField(default=0)),
                ('like_number', models.IntegerField(default=0)),
                ('share_number', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
