# Generated by Django 3.2.9 on 2021-11-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=20)),
                ('group', models.CharField(max_length=50)),
                ('intro', models.CharField(max_length=200)),
                ('image', models.CharField(default='img/profile/anonymous-user.png', max_length=200)),
            ],
        ),
    ]
