# Generated by Django 3.2.9 on 2021-11-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20211102_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.CharField(default='11/10/2021', max_length=30),
        ),
    ]
