# Generated by Django 3.2.9 on 2021-11-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20211103_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.CharField(max_length=30),
        ),
    ]
